import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:intl/intl.dart';
import '../../../core/theme/app_theme.dart';
import '../../../models/coupon_model.dart';
import '../../../services/admin_coupon_service.dart';
import '../../../core/utils/formatters.dart';

class AdminCouponFormScreen extends StatefulWidget {
  final CouponModel? existingCoupon;

  const AdminCouponFormScreen({super.key, this.existingCoupon});

  @override
  State<AdminCouponFormScreen> createState() => _AdminCouponFormScreenState();
}

class _AdminCouponFormScreenState extends State<AdminCouponFormScreen> {
  final _formKey = GlobalKey<FormState>();
  
  late final TextEditingController _codeController;
  late final TextEditingController _nameController;
  late final TextEditingController _descController;
  late final TextEditingController _discountController;
  late final TextEditingController _maxDiscountController;
  late final TextEditingController _minOrderController;
  late final TextEditingController _usageLimitController;
  late final TextEditingController _usageLimitPerUserController;

  String _discountType = 'percentage';
  String _customerEligibility = 'all';
  late DateTime _startDate;
  late DateTime _expiryDate;
  bool _isLoading = false;

  @override
  void initState() {
    super.initState();
    final c = widget.existingCoupon;
    
    _codeController = TextEditingController(text: c?.code ?? '');
    _nameController = TextEditingController(text: c?.name ?? '');
    _descController = TextEditingController(text: c?.description ?? '');
    
    _discountType = c?.discountType ?? 'percentage';
    
    // In paise, convert back to rupees for input
    _discountController = TextEditingController(
      text: c != null ? (c.discountType == 'percentage' ? c.discountAmount.toString() : (c.discountAmount / 100).toStringAsFixed(0)) : ''
    );
    _maxDiscountController = TextEditingController(
      text: (c != null && c.maxDiscountAmount > 0) ? (c.maxDiscountAmount / 100).toStringAsFixed(0) : ''
    );
    _minOrderController = TextEditingController(
      text: c != null ? (c.minOrderAmount / 100).toStringAsFixed(0) : ''
    );
    
    _usageLimitController = TextEditingController(text: c?.usageLimit?.toString() ?? '');
    _usageLimitPerUserController = TextEditingController(text: c?.usageLimitPerUser?.toString() ?? '');
    
    _customerEligibility = c?.customerEligibility ?? 'all';
    _startDate = c?.startDate ?? DateTime.now();
    _expiryDate = c?.expiryDate ?? DateTime.now().add(const Duration(days: 30));
  }

  @override
  void dispose() {
    _codeController.dispose();
    _nameController.dispose();
    _descController.dispose();
    _discountController.dispose();
    _maxDiscountController.dispose();
    _minOrderController.dispose();
    _usageLimitController.dispose();
    _usageLimitPerUserController.dispose();
    super.dispose();
  }

  void _submit() async {
    if (!_formKey.currentState!.validate()) return;
    setState(() => _isLoading = true);

    try {
      int discountValue = 0;
      if (_discountType == 'percentage') {
        discountValue = int.parse(_discountController.text.trim());
      } else {
        discountValue = (double.parse(_discountController.text.trim()) * 100).toInt();
      }

      int maxDiscount = 0;
      if (_maxDiscountController.text.trim().isNotEmpty) {
        maxDiscount = (double.parse(_maxDiscountController.text.trim()) * 100).toInt();
      }

      int minOrder = 0;
      if (_minOrderController.text.trim().isNotEmpty) {
        minOrder = (double.parse(_minOrderController.text.trim()) * 100).toInt();
      }

      final couponData = CouponModel(
        id: widget.existingCoupon?.id ?? '', // id will be generated by service if empty
        code: _codeController.text.trim().toUpperCase(),
        name: _nameController.text.trim(),
        description: _descController.text.trim(),
        discountType: _discountType,
        discountAmount: discountValue,
        maxDiscountAmount: maxDiscount,
        minOrderAmount: minOrder,
        isActive: widget.existingCoupon?.isActive ?? true,
        startDate: _startDate,
        expiryDate: _expiryDate,
        usageLimit: int.tryParse(_usageLimitController.text.trim()),
        usageLimitPerUser: int.tryParse(_usageLimitPerUserController.text.trim()),
        customerEligibility: _customerEligibility,
        createdAt: widget.existingCoupon?.createdAt ?? DateTime.now(),
      );

      if (widget.existingCoupon == null) {
        await AdminCouponService().addCoupon(couponData);
      } else {
        await AdminCouponService().editCoupon(widget.existingCoupon!.id, couponData);
      }

      if (mounted) context.pop();
    } catch (e) {
      if (mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Error: $e')));
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  Future<void> _pickDate(bool isStart) async {
    final initialDate = isStart ? _startDate : _expiryDate;
    final picked = await showDatePicker(
      context: context,
      initialDate: initialDate,
      firstDate: DateTime(2020),
      lastDate: DateTime(2100),
    );
    if (picked != null) {
      setState(() {
        if (isStart) _startDate = picked;
        else _expiryDate = picked;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    final isEditing = widget.existingCoupon != null;
    
    return Scaffold(
      backgroundColor: context.colors.background,
      appBar: AppBar(
        title: Text(isEditing ? 'Edit Coupon' : 'Add Coupon'),
        backgroundColor: context.colors.surface,
      ),
      body: Form(
        key: _formKey,
        child: ListView(
          padding: const EdgeInsets.all(16),
          children: [
            _buildSectionTitle('Basic Info'),
            _buildTextField(_codeController, 'Coupon Code (e.g. SUMMER50)', isRequired: true, textCapitalization: TextCapitalization.characters),
            _buildTextField(_nameController, 'Coupon Name (e.g. Summer Sale)', isRequired: true),
            _buildTextField(_descController, 'Description', maxLines: 3),
            
            const SizedBox(height: 24),
            _buildSectionTitle('Discount Details'),
            DropdownButtonFormField<String>(
              value: _discountType,
              decoration: _inputDecoration('Discount Type'),
              items: const [
                DropdownMenuItem(value: 'percentage', child: Text('Percentage (%)')),
                DropdownMenuItem(value: 'flat', child: Text('Flat Amount (₹)')),
                DropdownMenuItem(value: 'free_delivery', child: Text('Free Delivery')),
                DropdownMenuItem(value: 'first_order', child: Text('First Order')),
              ],
              onChanged: (val) {
                if (val != null) setState(() => _discountType = val);
              },
            ),
            const SizedBox(height: 12),
            if (_discountType != 'free_delivery') ...[
              _buildTextField(_discountController, _discountType == 'percentage' ? 'Discount Percentage (%)' : 'Discount Amount (₹)', isRequired: true, keyboardType: TextInputType.number),
              if (_discountType == 'percentage')
                _buildTextField(_maxDiscountController, 'Max Discount Amount (₹) [Optional]', keyboardType: TextInputType.number),
            ],
            _buildTextField(_minOrderController, 'Minimum Order Amount (₹)', keyboardType: TextInputType.number),

            const SizedBox(height: 24),
            _buildSectionTitle('Usage Limits & Eligibility'),
            _buildTextField(_usageLimitController, 'Total Usage Limit (Optional)', keyboardType: TextInputType.number),
            _buildTextField(_usageLimitPerUserController, 'Usage Limit Per User (Optional)', keyboardType: TextInputType.number),
            const SizedBox(height: 12),
            DropdownButtonFormField<String>(
              value: _customerEligibility,
              decoration: _inputDecoration('Customer Eligibility'),
              items: const [
                DropdownMenuItem(value: 'all', child: Text('All Users')),
                DropdownMenuItem(value: 'new', child: Text('New Buyers Only')),
                DropdownMenuItem(value: 'recent_buyers', child: Text('Recent Buyers')),
                DropdownMenuItem(value: 'past_buyers', child: Text('All Past Buyers')),
                DropdownMenuItem(value: 'existing', child: Text('Existing Customers')),
              ],
              onChanged: (val) {
                if (val != null) setState(() => _customerEligibility = val);
              },
            ),

            const SizedBox(height: 24),
            _buildSectionTitle('Validity'),
            Row(
              children: [
                Expanded(
                  child: ListTile(
                    contentPadding: EdgeInsets.zero,
                    title: const Text('Start Date', style: TextStyle(fontSize: 12)),
                    subtitle: Text(DateFormat('dd MMM yyyy').format(_startDate), style: const TextStyle(fontWeight: FontWeight.bold)),
                    trailing: const Icon(Icons.calendar_today, size: 20),
                    onTap: () => _pickDate(true),
                  ),
                ),
                const SizedBox(width: 16),
                Expanded(
                  child: ListTile(
                    contentPadding: EdgeInsets.zero,
                    title: const Text('Expiry Date', style: TextStyle(fontSize: 12)),
                    subtitle: Text(DateFormat('dd MMM yyyy').format(_expiryDate), style: const TextStyle(fontWeight: FontWeight.bold)),
                    trailing: const Icon(Icons.calendar_today, size: 20),
                    onTap: () => _pickDate(false),
                  ),
                ),
              ],
            ),

            const SizedBox(height: 32),
            ElevatedButton(
              style: ElevatedButton.styleFrom(
                backgroundColor: context.colors.primary,
                padding: const EdgeInsets.symmetric(vertical: 16),
                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
              ),
              onPressed: _isLoading ? null : _submit,
              child: _isLoading 
                  ? const CircularProgressIndicator(color: Colors.white)
                  : Text(isEditing ? 'Save Changes' : 'Create Coupon', style: const TextStyle(color: Colors.white, fontSize: 16, fontWeight: FontWeight.bold)),
            ),
            const SizedBox(height: 40),
          ],
        ),
      ),
    );
  }

  Widget _buildSectionTitle(String title) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 12),
      child: Text(
        title,
        style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold, color: context.colors.primary),
      ),
    );
  }

  Widget _buildTextField(TextEditingController controller, String label, {bool isRequired = false, int maxLines = 1, TextInputType? keyboardType, TextCapitalization textCapitalization = TextCapitalization.none}) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 12),
      child: TextFormField(
        controller: controller,
        maxLines: maxLines,
        keyboardType: keyboardType,
        textCapitalization: textCapitalization,
        decoration: _inputDecoration(label),
        validator: isRequired ? (v) => v!.isEmpty ? 'Required' : null : null,
      ),
    );
  }

  InputDecoration _inputDecoration(String label) {
    return InputDecoration(
      labelText: label,
      filled: true,
      fillColor: context.colors.surfaceGrey,
      border: OutlineInputBorder(borderRadius: BorderRadius.circular(12), borderSide: BorderSide.none),
    );
  }
}
